name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        NUGET_SERVER: ${{ secrets.NUGET_SERVER }}
#    - name: Restore dependencies
#      run: dotnet restore
    - name: Build
      run: dotnet build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish Nuget
      run: dotnet nuget push PocNugetSL.1.7.0.nupkg -k "$NUGET_KEY" -s "$NUGET_SERVER"
      
